CREATE TABLE IF NOT EXISTS sources (
  source_id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  DOI INTERGER UNIQUE,
    author NOT NULL TEXT,
    title NOT NULL TEXT,
    journal TEXT,
    year NOT NULL INTERGER,
    volume INTERGER,
    issue INTERGER,
    page_start INTERGER,
    page_end INTERGER,
    stable_url TEXT,
    date_accessed DATE,
phenotype_id REFERENCES phenotype(phenotype_id),
tolerance_id REFERENCES tolerance(tolerance_id),
species_organ_nutrient_id REFERENCES species_organ_nutrient(species_organ_nutrient_id),
);